<a href="https://colab.research.google.com/github/gogowonji/Big-Data-Analysis/blob/main/20230328_test07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
print(ar1)

[1 2 3 4 5]


In [ ]:
print(type(ar1))

<class 'numpy.ndarray'>


In [ ]:
ar2 = np.array([[10,20,30],[40,50,60]])
print(ar2)

[[10 20 30]
 [40 50 60]]


In [ ]:
# 배열 만들기 (1~10까지 2씩 건너뛰기)
ar3 = np.arange(1,11,2)
print(ar3)

[1 3 5 7 9]


In [ ]:
ar4 = np.array([1,2,3,4,5,6]).reshape(3,2)
print(ar4)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# 초기화
ar5 = np.zeros((2,3))
print(ar5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 범위 지정
ar6 = ar2[0:2,0:2]
print(ar6)

[[10 20]
 [40 50]]


In [ ]:
ar7 = ar1 + 10
print(ar7)

[11 12 13 14 15]


In [ ]:
print(ar1+ar7)

[12 14 16 18 20]


In [ ]:
print(ar7-ar1)

[10 10 10 10 10]


In [ ]:
print(ar1*2)

[ 2  4  6  8 10]


In [ ]:
print(ar1/2)

[0.5 1.  1.5 2.  2.5]


In [ ]:
# 행렬곱
ar8 = np.dot(ar2,ar4)
print(ar8)

[[220 280]
 [490 640]]
